# Generated by Django 4.1.10 on 2025-03-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobName', models.CharField(blank=True, max_length=1000, null=True)),
                ('RoleName', models.CharField(blank=True, max_length=100, null=True)),
                ('Aboutjob', models.TextField(blank=True, max_length=400, null=True)),
                ('Iconclassname', models.CharField(blank=True, max_length=1000, null=True)),
                ('dateandtime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(blank=True, max_length=1000, null=True)),
                ('Link', models.CharField(blank=True, max_length=2000, null=True)),
                ('dateandtime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
