# Generated by Django 4.1.10 on 2025-03-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='exp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
